services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: $UID:$GUID
    network_mode: 'host'
    volumes:
      - /drive/media3/jellyconfig:/config
      - /drive/media3/jellycache:/cache
      - /drive:/media
    restart: 'unless-stopped'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

