services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: $UID:$GUID
    network_mode: 'host'
    volumes:
      - /share:/config
      - /share:/cache
      - /share:/media
    restart: 'unless-stopped'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

